FROM postgres:14.8
ENV POSTGRES_USER=ubuntu
ENV POSTGRES_PASSWORD=forgot123
ENV POSTGRES_DB=leaderboard
ENV PGDATA=/data
RUN apt-get update && apt-get install -y postgis postgresql-14-postgis-3
EXPOSE 5432