FROM python:3.8
RUN apt-get update && apt-get install -y tesseract-ocr postgresql-client
RUN mkdir /code
WORKDIR /code
COPY requirements.txt /code/
RUN python3 -m pip install --upgrade pip
RUN pip install -r requirements.txt
COPY . /code/
ENTRYPOINT celery -A leaderboard beat --loglevel=debug 
