FROM python:3.12.1-bullseye
RUN apt-get update && apt-get install -y tesseract-ocr postgresql-client libpq-dev binutils libproj-dev gdal-bin wkhtmltopdf qpdf libqpdf-dev nginx libblas-dev liblapack-dev libatlas-base-dev gfortran-9
RUN mkdir /code
WORKDIR /code
COPY requirements.txt /code/
RUN python3 -m pip install --upgrade pip
RUN pip install -r requirements.txt
COPY . /code/
ENTRYPOINT celery -A leaderboard worker -l INFO
