# Generated by Django 3.2.23 on 2025-02-10 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamesession',
            name='duration_in_sec',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='historicalgamesession',
            name='duration_in_sec',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
