# Generated by Django 3.2.23 on 2025-02-10 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20250210_1316'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='upvotes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='historicalgame',
            name='upvotes',
            field=models.IntegerField(default=0),
        ),
    ]
