# Generated by Django 3.2.23 on 2025-02-10 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_auto_20250210_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='popularity_score',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='historicalgame',
            name='popularity_score',
            field=models.FloatField(default=0),
        ),
    ]
